# Generated by Django 4.1.7 on 2023-06-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
